### ISSUE TITLE
Support for Stackage

### ISSUE THREAD

**Issue by varosi** [JPMoresmau/scion-class-browser#16]
This way it will be compatible with stable Stackage libraries.
http://www.stackage.org/

**Comment by varosi** [comment]
Currently there is a problem with "persistent", since in latest stable version in LTS Haskell 1.0 is 2.1.1.3.
I tryed to get latest scion-class-browser sources and bump the persistent version, but I got this error:
[ 6 of 18] Compiling Scion.PersistentBrowser.DbTypes ( src\Scion\PersistentBrowser\DbTypes.hs, dist\dist-sandbox-b164f061\build\Scion\PersistentBrowser\DbTypes.
o )

src\Scion\PersistentBrowser\DbTypes.hs:20:1:
    Illegal instance declaration for
      `ToBackendKey SqlBackend DbConstructor'
      (Only one type can be given in an instance head.
       Use MultiParamTypeClasses if you want to allow more.)
    In the instance declaration for
      `ToBackendKey SqlBackend DbConstructor'

src\Scion\PersistentBrowser\DbTypes.hs:20:1:
    Illegal instance declaration for
      `ToBackendKey SqlBackend DbContext'
      (Only one type can be given in an instance head.
       Use MultiParamTypeClasses if you want to allow more.)
    In the instance declaration for `ToBackendKey SqlBackend DbContext'

src\Scion\PersistentBrowser\DbTypes.hs:20:1:
    Illegal instance declaration for `ToBackendKey SqlBackend DbFunDep'
      (Only one type can be given in an instance head.
       Use MultiParamTypeClasses if you want to allow more.)
    In the instance declaration for `ToBackendKey SqlBackend DbFunDep'

src\Scion\PersistentBrowser\DbTypes.hs:20:1:
    Illegal instance declaration for `ToBackendKey SqlBackend DbTyVar'
      (Only one type can be given in an instance head.
       Use MultiParamTypeClasses if you want to allow more.)
    In the instance declaration for `ToBackendKey SqlBackend DbTyVar'

src\Scion\PersistentBrowser\DbTypes.hs:20:1:
    Illegal instance declaration for `ToBackendKey SqlBackend DbDecl'
      (Only one type can be given in an instance head.
       Use MultiParamTypeClasses if you want to allow more.)
    In the instance declaration for `ToBackendKey SqlBackend DbDecl'

src\Scion\PersistentBrowser\DbTypes.hs:20:1:
    Illegal instance declaration for `ToBackendKey SqlBackend DbModule'
      (Only one type can be given in an instance head.
       Use MultiParamTypeClasses if you want to allow more.)
    In the instance declaration for `ToBackendKey SqlBackend DbModule'

src\Scion\PersistentBrowser\DbTypes.hs:20:1:
    Illegal instance declaration for
      `ToBackendKey SqlBackend DbPackage'
      (Only one type can be given in an instance head.
       Use MultiParamTypeClasses if you want to allow more.)
    In the instance declaration for `ToBackendKey SqlBackend DbPackage'

**Comment by varosi** [comment]
Even oldest LTS 0.2 is not supporting persistent < 2.1.

**Comment by varosi** [comment]
It seems that it is not so straight forward support for persistent 2.1. It is very different from 1.x.

**Comment by hartmut27** [comment]
Anybody an idea how to solve this issue?

**Comment by JPMoresmau** [comment]
Here's an idea: somebody forks the project in Github, spend five minutes fixing the issues and issues a pull request. Too late for that issue, but maybe something to keep in mind for another one!

**Comment by varosi** [comment]
I spent much more, but I don't know the whole logic and had no time to
finish the fix.
But it's great that it could used in sync with Stackage!!

2015-02-07 17:58 GMT+02:00 JP Moresmau <notifications@github.com>:
